// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Allergen struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	RegulatoryGroup pgtype.Text        `json:"regulatory_group"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AllergenTranslation struct {
	AllergenID pgtype.UUID `json:"allergen_id"`
	Locale     string      `json:"locale"`
	Name       string      `json:"name"`
}

type AppUser struct {
	ID                  pgtype.UUID        `json:"id"`
	ExternalID          pgtype.Text        `json:"external_id"`
	DisplayName         string             `json:"display_name"`
	Email               pgtype.Text        `json:"email"`
	PreferredUnitSystem string             `json:"preferred_unit_system"`
	PreferredLocale     string             `json:"preferred_locale"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type CompiledRecipe struct {
	RecipeID                    pgtype.UUID        `json:"recipe_id"`
	CompiledAt                  pgtype.Timestamptz `json:"compiled_at"`
	IsStale                     bool               `json:"is_stale"`
	CompiledSteps               []byte             `json:"compiled_steps"`
	CompiledGroceryList         []byte             `json:"compiled_grocery_list"`
	CompiledNutritionPerServing []byte             `json:"compiled_nutrition_per_serving"`
	CompiledNutritionTotal      []byte             `json:"compiled_nutrition_total"`
	CompiledAllergens           []string           `json:"compiled_allergens"`
	CompiledDietFlags           []string           `json:"compiled_diet_flags"`
	TotalActiveSeconds          int32              `json:"total_active_seconds"`
	TotalPassiveSeconds         int32              `json:"total_passive_seconds"`
	TotalCaloriesPerServing     pgtype.Numeric     `json:"total_calories_per_serving"`
	CompiledTags                []string           `json:"compiled_tags"`
	CompiledFromRevisionID      pgtype.UUID        `json:"compiled_from_revision_id"`
	CompiledAllergensContains   []string           `json:"compiled_allergens_contains"`
	CompiledAllergensMayContain []string           `json:"compiled_allergens_may_contain"`
	CompileInputHash            pgtype.Text        `json:"compile_input_hash"`
	CompileSchemaVersion        int32              `json:"compile_schema_version"`
}

type DietFlag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DietFlagTranslation struct {
	DietFlagID pgtype.UUID `json:"diet_flag_id"`
	Locale     string      `json:"locale"`
	Name       string      `json:"name"`
}

type Ingredient struct {
	ID              pgtype.UUID        `json:"id"`
	FdcID           pgtype.Int4        `json:"fdc_id"`
	OpenFoodFactsID pgtype.Text        `json:"open_food_facts_id"`
	Name            string             `json:"name"`
	NameSlug        string             `json:"name_slug"`
	FoodGroup       pgtype.Text        `json:"food_group"`
	DefaultUnitID   pgtype.UUID        `json:"default_unit_id"`
	DataSources     []byte             `json:"data_sources"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type IngredientAllergen struct {
	IngredientID pgtype.UUID `json:"ingredient_id"`
	AllergenID   pgtype.UUID `json:"allergen_id"`
	Severity     string      `json:"severity"`
}

type IngredientDensity struct {
	ID            pgtype.UUID        `json:"id"`
	IngredientID  pgtype.UUID        `json:"ingredient_id"`
	DensityGPerMl pgtype.Numeric     `json:"density_g_per_ml"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IngredientDietFlag struct {
	IngredientID pgtype.UUID `json:"ingredient_id"`
	DietFlagID   pgtype.UUID `json:"diet_flag_id"`
	Compatible   bool        `json:"compatible"`
}

type IngredientLibrary struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerType string             `json:"owner_type"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IngredientLibraryItem struct {
	LibraryID    pgtype.UUID        `json:"library_id"`
	IngredientID pgtype.UUID        `json:"ingredient_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type IngredientNutrient struct {
	IngredientID  pgtype.UUID    `json:"ingredient_id"`
	NutrientID    pgtype.UUID    `json:"nutrient_id"`
	AmountPer100g pgtype.Numeric `json:"amount_per_100g"`
	DataSource    pgtype.Text    `json:"data_source"`
}

type IngredientPortion struct {
	ID           pgtype.UUID        `json:"id"`
	IngredientID pgtype.UUID        `json:"ingredient_id"`
	UnitID       pgtype.UUID        `json:"unit_id"`
	GramsPerUnit pgtype.Numeric     `json:"grams_per_unit"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type IngredientPrice struct {
	ID           pgtype.UUID        `json:"id"`
	IngredientID pgtype.UUID        `json:"ingredient_id"`
	ScopeType    string             `json:"scope_type"`
	ScopeID      pgtype.UUID        `json:"scope_id"`
	CurrencyCode string             `json:"currency_code"`
	PricePerKg   pgtype.Numeric     `json:"price_per_kg"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	Source       pgtype.Text        `json:"source"`
}

type IngredientTranslation struct {
	IngredientID pgtype.UUID `json:"ingredient_id"`
	Locale       string      `json:"locale"`
	Name         string      `json:"name"`
}

type MealPlan struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     string             `json:"title"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MealPlanItem struct {
	ID          pgtype.UUID        `json:"id"`
	MealPlanID  pgtype.UUID        `json:"meal_plan_id"`
	RecipeID    pgtype.UUID        `json:"recipe_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	MealType    pgtype.Text        `json:"meal_type"`
	Servings    pgtype.Numeric     `json:"servings"`
}

type Nutrient struct {
	ID                pgtype.UUID        `json:"id"`
	FdcNutrientID     pgtype.Int4        `json:"fdc_nutrient_id"`
	FdcNutrientNumber pgtype.Text        `json:"fdc_nutrient_number"`
	Name              string             `json:"name"`
	Unit              string             `json:"unit"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	DisplayRank       int32              `json:"display_rank"`
	IsDisplayed       bool               `json:"is_displayed"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type NutrientCategory struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type NutrientTranslation struct {
	NutrientID pgtype.UUID `json:"nutrient_id"`
	Locale     string      `json:"locale"`
	Name       string      `json:"name"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Recipe struct {
	ID           pgtype.UUID        `json:"id"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	Servings     int32              `json:"servings"`
	Visibility   string             `json:"visibility"`
	SourceLocale string             `json:"source_locale"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	YieldAmount  pgtype.Numeric     `json:"yield_amount"`
	YieldUnitID  pgtype.UUID        `json:"yield_unit_id"`
}

type RecipeClosure struct {
	AncestorRecipeID   pgtype.UUID `json:"ancestor_recipe_id"`
	DescendantRecipeID pgtype.UUID `json:"descendant_recipe_id"`
	Depth              int32       `json:"depth"`
}

type RecipeFork struct {
	ForkedRecipeID pgtype.UUID        `json:"forked_recipe_id"`
	ParentRecipeID pgtype.UUID        `json:"parent_recipe_id"`
	ForkedBy       pgtype.UUID        `json:"forked_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RecipeMedium struct {
	ID        pgtype.UUID        `json:"id"`
	RecipeID  pgtype.UUID        `json:"recipe_id"`
	Url       string             `json:"url"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecipeMembership struct {
	RecipeID  pgtype.UUID        `json:"recipe_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecipePermission struct {
	RecipeID      pgtype.UUID        `json:"recipe_id"`
	PrincipalType string             `json:"principal_type"`
	PrincipalID   pgtype.UUID        `json:"principal_id"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RecipeReviewRating struct {
	RecipeID   pgtype.UUID        `json:"recipe_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Rating     int32              `json:"rating"`
	ReviewText pgtype.Text        `json:"review_text"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RecipeRevision struct {
	ID         pgtype.UUID        `json:"id"`
	RecipeID   pgtype.UUID        `json:"recipe_id"`
	RevisionNo int32              `json:"revision_no"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RecipeStep struct {
	ID              pgtype.UUID `json:"id"`
	RecipeID        pgtype.UUID `json:"recipe_id"`
	Position        int32       `json:"position"`
	Instruction     string      `json:"instruction"`
	ActiveSeconds   int32       `json:"active_seconds"`
	PassiveSeconds  int32       `json:"passive_seconds"`
	MakeAheadNote   pgtype.Text `json:"make_ahead_note"`
	CanPrepareAhead bool        `json:"can_prepare_ahead"`
}

type RecipeStepComponent struct {
	ID              pgtype.UUID    `json:"id"`
	StepID          pgtype.UUID    `json:"step_id"`
	Position        int32          `json:"position"`
	IngredientID    pgtype.UUID    `json:"ingredient_id"`
	SubRecipeID     pgtype.UUID    `json:"sub_recipe_id"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitID          pgtype.UUID    `json:"unit_id"`
	Optional        bool           `json:"optional"`
	PreparationNote pgtype.Text    `json:"preparation_note"`
}

type RecipeTag struct {
	RecipeID pgtype.UUID `json:"recipe_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

type RecipeTranslation struct {
	RecipeID    pgtype.UUID `json:"recipe_id"`
	Locale      string      `json:"locale"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

type ShoppingList struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShoppingListItem struct {
	ID             pgtype.UUID    `json:"id"`
	ShoppingListID pgtype.UUID    `json:"shopping_list_id"`
	IngredientID   pgtype.UUID    `json:"ingredient_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	UnitID         pgtype.UUID    `json:"unit_id"`
	Checked        bool           `json:"checked"`
	Note           pgtype.Text    `json:"note"`
}

type ShoppingListRecipeItem struct {
	ShoppingListID pgtype.UUID    `json:"shopping_list_id"`
	RecipeID       pgtype.UUID    `json:"recipe_id"`
	Servings       pgtype.Numeric `json:"servings"`
}

type StepEquipment struct {
	StepID        pgtype.UUID `json:"step_id"`
	EquipmentName string      `json:"equipment_name"`
}

type StepTranslation struct {
	StepID      pgtype.UUID `json:"step_id"`
	Locale      string      `json:"locale"`
	Instruction string      `json:"instruction"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Category  string             `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TagTranslation struct {
	TagID  pgtype.UUID `json:"tag_id"`
	Locale string      `json:"locale"`
	Name   string      `json:"name"`
}

type Unit struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	NamePlural   string             `json:"name_plural"`
	System       string             `json:"system"`
	Dimension    string             `json:"dimension"`
	ToBaseFactor pgtype.Numeric     `json:"to_base_factor"`
	ToBaseOffset pgtype.Numeric     `json:"to_base_offset"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UnitTranslation struct {
	UnitID     pgtype.UUID `json:"unit_id"`
	Locale     string      `json:"locale"`
	Name       string      `json:"name"`
	NamePlural string      `json:"name_plural"`
}
