// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRecipeTag = `-- name: AddRecipeTag :exec
INSERT INTO recipe_tags (recipe_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRecipeTagParams struct {
	RecipeID pgtype.UUID `json:"recipe_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddRecipeTag(ctx context.Context, arg AddRecipeTagParams) error {
	_, err := q.db.Exec(ctx, addRecipeTag, arg.RecipeID, arg.TagID)
	return err
}

const collectRecipeAllergens = `-- name: CollectRecipeAllergens :many
WITH RECURSIVE recipe_tree AS (
    SELECT rsc.ingredient_id, rsc.sub_recipe_id, 1.0::numeric AS multiplier, rsc.quantity
    FROM recipe_steps rs
    JOIN recipe_step_components rsc ON rsc.step_id = rs.id
    WHERE rs.recipe_id = $1
    UNION ALL
    SELECT rsc.ingredient_id, rsc.sub_recipe_id,
           rt.multiplier * (rt.quantity / NULLIF(COALESCE(r.yield_amount, r.servings::numeric), 0)),
           rsc.quantity
    FROM recipe_tree rt
    JOIN recipes r ON r.id = rt.sub_recipe_id
    JOIN recipe_steps rs ON rs.recipe_id = r.id
    JOIN recipe_step_components rsc ON rsc.step_id = rs.id
    WHERE rt.sub_recipe_id IS NOT NULL
)
SELECT DISTINCT a.name
FROM recipe_tree rt
JOIN ingredient_allergens ia ON ia.ingredient_id = rt.ingredient_id
JOIN allergens a ON a.id = ia.allergen_id
WHERE rt.ingredient_id IS NOT NULL AND ia.severity = 'contains'
`

// Collects all allergens for a recipe by traversing sub-recipes.
func (q *Queries) CollectRecipeAllergens(ctx context.Context, recipeID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, collectRecipeAllergens, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectRecipeDietFlags = `-- name: CollectRecipeDietFlags :many
WITH RECURSIVE recipe_tree AS (
    SELECT rsc.ingredient_id, rsc.sub_recipe_id, 1.0::numeric AS multiplier, rsc.quantity
    FROM recipe_steps rs
    JOIN recipe_step_components rsc ON rsc.step_id = rs.id
    WHERE rs.recipe_id = $1
    UNION ALL
    SELECT rsc.ingredient_id, rsc.sub_recipe_id,
           rt.multiplier * (rt.quantity / NULLIF(COALESCE(r.yield_amount, r.servings::numeric), 0)),
           rsc.quantity
    FROM recipe_tree rt
    JOIN recipes r ON r.id = rt.sub_recipe_id
    JOIN recipe_steps rs ON rs.recipe_id = r.id
    JOIN recipe_step_components rsc ON rsc.step_id = rs.id
    WHERE rt.sub_recipe_id IS NOT NULL
)
SELECT df.name
FROM diet_flags df
WHERE NOT EXISTS (
    -- No ingredient that lacks a compatible=true row for this flag
    SELECT 1
    FROM recipe_tree rt
    WHERE rt.ingredient_id IS NOT NULL
    AND NOT EXISTS (
        SELECT 1 FROM ingredient_diet_flags idf
        WHERE idf.ingredient_id = rt.ingredient_id
        AND idf.diet_flag_id = df.id
        AND idf.compatible = true
    )
)
AND EXISTS (
    SELECT 1
    FROM recipe_tree rt
    WHERE rt.ingredient_id IS NOT NULL
)
`

// Determines diet compatibility: a recipe is compatible with a diet
// only if ALL its ingredients explicitly have compatible=true for that flag.
// Missing data (no row in ingredient_diet_flags) means NOT compatible.
func (q *Queries) CollectRecipeDietFlags(ctx context.Context, recipeID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, collectRecipeDietFlags, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompiledRecipe = `-- name: GetCompiledRecipe :one
SELECT cr.recipe_id, cr.compiled_at, cr.is_stale,
       cr.compiled_steps, cr.compiled_grocery_list,
       cr.compiled_nutrition_per_serving, cr.compiled_nutrition_total,
       cr.compiled_allergens, cr.compiled_diet_flags,
       cr.total_active_seconds, cr.total_passive_seconds, cr.total_calories_per_serving,
       cr.compiled_tags, cr.compiled_from_revision_id,
       cr.compiled_allergens_contains, cr.compiled_allergens_may_contain, cr.compile_input_hash,
       cr.compile_schema_version,
       r.title, r.slug, r.description, r.servings, r.yield_amount, r.yield_unit_id,
       r.source_locale, r.visibility,
       r.author_id, r.created_at AS recipe_created_at, r.updated_at AS recipe_updated_at
FROM compiled_recipes cr
JOIN recipes r ON r.id = cr.recipe_id
WHERE cr.recipe_id = $1
`

type GetCompiledRecipeRow struct {
	RecipeID                    pgtype.UUID        `json:"recipe_id"`
	CompiledAt                  pgtype.Timestamptz `json:"compiled_at"`
	IsStale                     bool               `json:"is_stale"`
	CompiledSteps               []byte             `json:"compiled_steps"`
	CompiledGroceryList         []byte             `json:"compiled_grocery_list"`
	CompiledNutritionPerServing []byte             `json:"compiled_nutrition_per_serving"`
	CompiledNutritionTotal      []byte             `json:"compiled_nutrition_total"`
	CompiledAllergens           []string           `json:"compiled_allergens"`
	CompiledDietFlags           []string           `json:"compiled_diet_flags"`
	TotalActiveSeconds          int32              `json:"total_active_seconds"`
	TotalPassiveSeconds         int32              `json:"total_passive_seconds"`
	TotalCaloriesPerServing     pgtype.Numeric     `json:"total_calories_per_serving"`
	CompiledTags                []string           `json:"compiled_tags"`
	CompiledFromRevisionID      pgtype.UUID        `json:"compiled_from_revision_id"`
	CompiledAllergensContains   []string           `json:"compiled_allergens_contains"`
	CompiledAllergensMayContain []string           `json:"compiled_allergens_may_contain"`
	CompileInputHash            pgtype.Text        `json:"compile_input_hash"`
	CompileSchemaVersion        int32              `json:"compile_schema_version"`
	Title                       string             `json:"title"`
	Slug                        string             `json:"slug"`
	Description                 pgtype.Text        `json:"description"`
	Servings                    int32              `json:"servings"`
	YieldAmount                 pgtype.Numeric     `json:"yield_amount"`
	YieldUnitID                 pgtype.UUID        `json:"yield_unit_id"`
	SourceLocale                string             `json:"source_locale"`
	Visibility                  string             `json:"visibility"`
	AuthorID                    pgtype.UUID        `json:"author_id"`
	RecipeCreatedAt             pgtype.Timestamptz `json:"recipe_created_at"`
	RecipeUpdatedAt             pgtype.Timestamptz `json:"recipe_updated_at"`
}

func (q *Queries) GetCompiledRecipe(ctx context.Context, recipeID pgtype.UUID) (GetCompiledRecipeRow, error) {
	row := q.db.QueryRow(ctx, getCompiledRecipe, recipeID)
	var i GetCompiledRecipeRow
	err := row.Scan(
		&i.RecipeID,
		&i.CompiledAt,
		&i.IsStale,
		&i.CompiledSteps,
		&i.CompiledGroceryList,
		&i.CompiledNutritionPerServing,
		&i.CompiledNutritionTotal,
		&i.CompiledAllergens,
		&i.CompiledDietFlags,
		&i.TotalActiveSeconds,
		&i.TotalPassiveSeconds,
		&i.TotalCaloriesPerServing,
		&i.CompiledTags,
		&i.CompiledFromRevisionID,
		&i.CompiledAllergensContains,
		&i.CompiledAllergensMayContain,
		&i.CompileInputHash,
		&i.CompileSchemaVersion,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Servings,
		&i.YieldAmount,
		&i.YieldUnitID,
		&i.SourceLocale,
		&i.Visibility,
		&i.AuthorID,
		&i.RecipeCreatedAt,
		&i.RecipeUpdatedAt,
	)
	return i, err
}

const getCompiledRecipeBySlug = `-- name: GetCompiledRecipeBySlug :one
SELECT cr.recipe_id, cr.compiled_at, cr.is_stale,
       cr.compiled_steps, cr.compiled_grocery_list,
       cr.compiled_nutrition_per_serving, cr.compiled_nutrition_total,
       cr.compiled_allergens, cr.compiled_diet_flags,
       cr.total_active_seconds, cr.total_passive_seconds, cr.total_calories_per_serving,
       cr.compiled_tags, cr.compiled_from_revision_id,
       cr.compiled_allergens_contains, cr.compiled_allergens_may_contain, cr.compile_input_hash,
       cr.compile_schema_version,
       r.title, r.slug, r.description, r.servings, r.yield_amount, r.yield_unit_id,
       r.source_locale, r.visibility,
       r.author_id, r.created_at AS recipe_created_at, r.updated_at AS recipe_updated_at
FROM compiled_recipes cr
JOIN recipes r ON r.id = cr.recipe_id
WHERE r.slug = $1
`

type GetCompiledRecipeBySlugRow struct {
	RecipeID                    pgtype.UUID        `json:"recipe_id"`
	CompiledAt                  pgtype.Timestamptz `json:"compiled_at"`
	IsStale                     bool               `json:"is_stale"`
	CompiledSteps               []byte             `json:"compiled_steps"`
	CompiledGroceryList         []byte             `json:"compiled_grocery_list"`
	CompiledNutritionPerServing []byte             `json:"compiled_nutrition_per_serving"`
	CompiledNutritionTotal      []byte             `json:"compiled_nutrition_total"`
	CompiledAllergens           []string           `json:"compiled_allergens"`
	CompiledDietFlags           []string           `json:"compiled_diet_flags"`
	TotalActiveSeconds          int32              `json:"total_active_seconds"`
	TotalPassiveSeconds         int32              `json:"total_passive_seconds"`
	TotalCaloriesPerServing     pgtype.Numeric     `json:"total_calories_per_serving"`
	CompiledTags                []string           `json:"compiled_tags"`
	CompiledFromRevisionID      pgtype.UUID        `json:"compiled_from_revision_id"`
	CompiledAllergensContains   []string           `json:"compiled_allergens_contains"`
	CompiledAllergensMayContain []string           `json:"compiled_allergens_may_contain"`
	CompileInputHash            pgtype.Text        `json:"compile_input_hash"`
	CompileSchemaVersion        int32              `json:"compile_schema_version"`
	Title                       string             `json:"title"`
	Slug                        string             `json:"slug"`
	Description                 pgtype.Text        `json:"description"`
	Servings                    int32              `json:"servings"`
	YieldAmount                 pgtype.Numeric     `json:"yield_amount"`
	YieldUnitID                 pgtype.UUID        `json:"yield_unit_id"`
	SourceLocale                string             `json:"source_locale"`
	Visibility                  string             `json:"visibility"`
	AuthorID                    pgtype.UUID        `json:"author_id"`
	RecipeCreatedAt             pgtype.Timestamptz `json:"recipe_created_at"`
	RecipeUpdatedAt             pgtype.Timestamptz `json:"recipe_updated_at"`
}

func (q *Queries) GetCompiledRecipeBySlug(ctx context.Context, slug string) (GetCompiledRecipeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCompiledRecipeBySlug, slug)
	var i GetCompiledRecipeBySlugRow
	err := row.Scan(
		&i.RecipeID,
		&i.CompiledAt,
		&i.IsStale,
		&i.CompiledSteps,
		&i.CompiledGroceryList,
		&i.CompiledNutritionPerServing,
		&i.CompiledNutritionTotal,
		&i.CompiledAllergens,
		&i.CompiledDietFlags,
		&i.TotalActiveSeconds,
		&i.TotalPassiveSeconds,
		&i.TotalCaloriesPerServing,
		&i.CompiledTags,
		&i.CompiledFromRevisionID,
		&i.CompiledAllergensContains,
		&i.CompiledAllergensMayContain,
		&i.CompileInputHash,
		&i.CompileSchemaVersion,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Servings,
		&i.YieldAmount,
		&i.YieldUnitID,
		&i.SourceLocale,
		&i.Visibility,
		&i.AuthorID,
		&i.RecipeCreatedAt,
		&i.RecipeUpdatedAt,
	)
	return i, err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, author_id, title, slug, description, servings, visibility, source_locale, created_at, updated_at, yield_amount, yield_unit_id FROM recipes WHERE id = $1
`

func (q *Queries) GetRecipeByID(ctx context.Context, id pgtype.UUID) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Servings,
		&i.Visibility,
		&i.SourceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.YieldAmount,
		&i.YieldUnitID,
	)
	return i, err
}

const getRecipeBySlug = `-- name: GetRecipeBySlug :one
SELECT id, author_id, title, slug, description, servings, visibility, source_locale, created_at, updated_at, yield_amount, yield_unit_id FROM recipes WHERE slug = $1
`

func (q *Queries) GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeBySlug, slug)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Servings,
		&i.Visibility,
		&i.SourceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.YieldAmount,
		&i.YieldUnitID,
	)
	return i, err
}

const listAllRecipeIDs = `-- name: ListAllRecipeIDs :many
SELECT id FROM recipes ORDER BY created_at
`

func (q *Queries) ListAllRecipeIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllRecipeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompiledRecipes = `-- name: ListCompiledRecipes :many
SELECT cr.recipe_id, cr.compiled_at, cr.is_stale,
       cr.compiled_steps, cr.compiled_grocery_list,
       cr.compiled_nutrition_per_serving, cr.compiled_nutrition_total,
       cr.compiled_allergens, cr.compiled_diet_flags,
       cr.total_active_seconds, cr.total_passive_seconds, cr.total_calories_per_serving,
       cr.compiled_tags, cr.compiled_from_revision_id,
       cr.compiled_allergens_contains, cr.compiled_allergens_may_contain, cr.compile_input_hash,
       cr.compile_schema_version,
       r.title, r.slug, r.description, r.servings, r.yield_amount, r.yield_unit_id,
       r.source_locale, r.visibility,
       r.author_id, r.created_at AS recipe_created_at, r.updated_at AS recipe_updated_at
FROM compiled_recipes cr
JOIN recipes r ON r.id = cr.recipe_id
WHERE r.visibility = 'public'
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCompiledRecipesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCompiledRecipesRow struct {
	RecipeID                    pgtype.UUID        `json:"recipe_id"`
	CompiledAt                  pgtype.Timestamptz `json:"compiled_at"`
	IsStale                     bool               `json:"is_stale"`
	CompiledSteps               []byte             `json:"compiled_steps"`
	CompiledGroceryList         []byte             `json:"compiled_grocery_list"`
	CompiledNutritionPerServing []byte             `json:"compiled_nutrition_per_serving"`
	CompiledNutritionTotal      []byte             `json:"compiled_nutrition_total"`
	CompiledAllergens           []string           `json:"compiled_allergens"`
	CompiledDietFlags           []string           `json:"compiled_diet_flags"`
	TotalActiveSeconds          int32              `json:"total_active_seconds"`
	TotalPassiveSeconds         int32              `json:"total_passive_seconds"`
	TotalCaloriesPerServing     pgtype.Numeric     `json:"total_calories_per_serving"`
	CompiledTags                []string           `json:"compiled_tags"`
	CompiledFromRevisionID      pgtype.UUID        `json:"compiled_from_revision_id"`
	CompiledAllergensContains   []string           `json:"compiled_allergens_contains"`
	CompiledAllergensMayContain []string           `json:"compiled_allergens_may_contain"`
	CompileInputHash            pgtype.Text        `json:"compile_input_hash"`
	CompileSchemaVersion        int32              `json:"compile_schema_version"`
	Title                       string             `json:"title"`
	Slug                        string             `json:"slug"`
	Description                 pgtype.Text        `json:"description"`
	Servings                    int32              `json:"servings"`
	YieldAmount                 pgtype.Numeric     `json:"yield_amount"`
	YieldUnitID                 pgtype.UUID        `json:"yield_unit_id"`
	SourceLocale                string             `json:"source_locale"`
	Visibility                  string             `json:"visibility"`
	AuthorID                    pgtype.UUID        `json:"author_id"`
	RecipeCreatedAt             pgtype.Timestamptz `json:"recipe_created_at"`
	RecipeUpdatedAt             pgtype.Timestamptz `json:"recipe_updated_at"`
}

func (q *Queries) ListCompiledRecipes(ctx context.Context, arg ListCompiledRecipesParams) ([]ListCompiledRecipesRow, error) {
	rows, err := q.db.Query(ctx, listCompiledRecipes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompiledRecipesRow{}
	for rows.Next() {
		var i ListCompiledRecipesRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.CompiledAt,
			&i.IsStale,
			&i.CompiledSteps,
			&i.CompiledGroceryList,
			&i.CompiledNutritionPerServing,
			&i.CompiledNutritionTotal,
			&i.CompiledAllergens,
			&i.CompiledDietFlags,
			&i.TotalActiveSeconds,
			&i.TotalPassiveSeconds,
			&i.TotalCaloriesPerServing,
			&i.CompiledTags,
			&i.CompiledFromRevisionID,
			&i.CompiledAllergensContains,
			&i.CompiledAllergensMayContain,
			&i.CompileInputHash,
			&i.CompileSchemaVersion,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Servings,
			&i.YieldAmount,
			&i.YieldUnitID,
			&i.SourceLocale,
			&i.Visibility,
			&i.AuthorID,
			&i.RecipeCreatedAt,
			&i.RecipeUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicRecipes = `-- name: ListPublicRecipes :many
SELECT id, author_id, title, slug, description, servings, visibility, source_locale, created_at, updated_at, yield_amount, yield_unit_id FROM recipes
WHERE visibility = 'public'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicRecipesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicRecipes(ctx context.Context, arg ListPublicRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listPublicRecipes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Servings,
			&i.Visibility,
			&i.SourceLocale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.YieldAmount,
			&i.YieldUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeSteps = `-- name: ListRecipeSteps :many
SELECT id, recipe_id, position, instruction, active_seconds, passive_seconds, make_ahead_note, can_prepare_ahead FROM recipe_steps
WHERE recipe_id = $1
ORDER BY position
`

func (q *Queries) ListRecipeSteps(ctx context.Context, recipeID pgtype.UUID) ([]RecipeStep, error) {
	rows, err := q.db.Query(ctx, listRecipeSteps, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeStep{}
	for rows.Next() {
		var i RecipeStep
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Position,
			&i.Instruction,
			&i.ActiveSeconds,
			&i.PassiveSeconds,
			&i.MakeAheadNote,
			&i.CanPrepareAhead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeTags = `-- name: ListRecipeTags :many
SELECT t.name, t.category
FROM recipe_tags rtag
JOIN tags t ON t.id = rtag.tag_id
WHERE rtag.recipe_id = $1
ORDER BY t.category, t.name
`

type ListRecipeTagsRow struct {
	Name     string `json:"name"`
	Category string `json:"category"`
}

func (q *Queries) ListRecipeTags(ctx context.Context, recipeID pgtype.UUID) ([]ListRecipeTagsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeTags, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeTagsRow{}
	for rows.Next() {
		var i ListRecipeTagsRow
		if err := rows.Scan(&i.Name, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRecipeIDs = `-- name: ListStaleRecipeIDs :many
SELECT r.id
FROM recipes r
LEFT JOIN compiled_recipes cr ON cr.recipe_id = r.id
WHERE cr.recipe_id IS NULL OR cr.is_stale = true
ORDER BY COALESCE(cr.compiled_at, r.created_at)
`

func (q *Queries) ListStaleRecipeIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleRecipeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepComponents = `-- name: ListStepComponents :many
SELECT
    rsc.id, rsc.step_id, rsc.position, rsc.ingredient_id, rsc.sub_recipe_id, rsc.quantity, rsc.unit_id, rsc.optional, rsc.preparation_note,
    i.name AS ingredient_name,
    i.name_slug AS ingredient_slug,
    u.name AS unit_name,
    u.name_plural AS unit_name_plural,
    sr.title AS sub_recipe_title,
    sr.slug AS sub_recipe_slug
FROM recipe_step_components rsc
JOIN units u ON u.id = rsc.unit_id
LEFT JOIN ingredients i ON i.id = rsc.ingredient_id
LEFT JOIN recipes sr ON sr.id = rsc.sub_recipe_id
WHERE rsc.step_id = $1
ORDER BY rsc.position
`

type ListStepComponentsRow struct {
	ID              pgtype.UUID    `json:"id"`
	StepID          pgtype.UUID    `json:"step_id"`
	Position        int32          `json:"position"`
	IngredientID    pgtype.UUID    `json:"ingredient_id"`
	SubRecipeID     pgtype.UUID    `json:"sub_recipe_id"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitID          pgtype.UUID    `json:"unit_id"`
	Optional        bool           `json:"optional"`
	PreparationNote pgtype.Text    `json:"preparation_note"`
	IngredientName  pgtype.Text    `json:"ingredient_name"`
	IngredientSlug  pgtype.Text    `json:"ingredient_slug"`
	UnitName        string         `json:"unit_name"`
	UnitNamePlural  string         `json:"unit_name_plural"`
	SubRecipeTitle  pgtype.Text    `json:"sub_recipe_title"`
	SubRecipeSlug   pgtype.Text    `json:"sub_recipe_slug"`
}

func (q *Queries) ListStepComponents(ctx context.Context, stepID pgtype.UUID) ([]ListStepComponentsRow, error) {
	rows, err := q.db.Query(ctx, listStepComponents, stepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepComponentsRow{}
	for rows.Next() {
		var i ListStepComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Position,
			&i.IngredientID,
			&i.SubRecipeID,
			&i.Quantity,
			&i.UnitID,
			&i.Optional,
			&i.PreparationNote,
			&i.IngredientName,
			&i.IngredientSlug,
			&i.UnitName,
			&i.UnitNamePlural,
			&i.SubRecipeTitle,
			&i.SubRecipeSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecipeTag = `-- name: RemoveRecipeTag :exec
DELETE FROM recipe_tags WHERE recipe_id = $1 AND tag_id = $2
`

type RemoveRecipeTagParams struct {
	RecipeID pgtype.UUID `json:"recipe_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveRecipeTag(ctx context.Context, arg RemoveRecipeTagParams) error {
	_, err := q.db.Exec(ctx, removeRecipeTag, arg.RecipeID, arg.TagID)
	return err
}

const resolveRecipeTree = `-- name: ResolveRecipeTree :many
WITH RECURSIVE recipe_tree AS (
    SELECT
        rsc.ingredient_id,
        rsc.sub_recipe_id,
        rsc.quantity,
        rsc.unit_id,
        1.0::numeric AS multiplier
    FROM recipe_steps rs
    JOIN recipe_step_components rsc ON rsc.step_id = rs.id
    WHERE rs.recipe_id = $1

    UNION ALL

    SELECT
        rsc.ingredient_id,
        rsc.sub_recipe_id,
        rsc.quantity,
        rsc.unit_id,
        rt.multiplier * (rt.quantity / NULLIF(COALESCE(r.yield_amount, r.servings::numeric), 0))
    FROM recipe_tree rt
    JOIN recipes r ON r.id = rt.sub_recipe_id
    JOIN recipe_steps rs ON rs.recipe_id = r.id
    JOIN recipe_step_components rsc ON rsc.step_id = rs.id
    WHERE rt.sub_recipe_id IS NOT NULL
),
normalized AS (
    SELECT
        rt.ingredient_id,
        CASE
            WHEN rt.unit_id = COALESCE(i.default_unit_id, rt.unit_id) THEN COALESCE(i.default_unit_id, rt.unit_id)
            WHEN su.dimension = du.dimension THEN COALESCE(i.default_unit_id, rt.unit_id)
            WHEN su.dimension = 'volume' AND du.dimension = 'mass' AND id_dens.density_g_per_ml IS NOT NULL THEN COALESCE(i.default_unit_id, rt.unit_id)
            WHEN su.dimension = 'mass' AND du.dimension = 'volume' AND id_dens.density_g_per_ml IS NOT NULL THEN COALESCE(i.default_unit_id, rt.unit_id)
            ELSE rt.unit_id
        END AS unit_id,
        CASE
            -- Same unit: no conversion needed
            WHEN rt.unit_id = COALESCE(i.default_unit_id, rt.unit_id) THEN
                rt.quantity * rt.multiplier
            -- Same dimension: convert via base factor ratio
            WHEN su.dimension = du.dimension THEN
                rt.quantity * rt.multiplier * su.to_base_factor / NULLIF(du.to_base_factor, 0)
            -- Cross-dimension (volume<->mass): use density
            WHEN su.dimension = 'volume' AND du.dimension = 'mass' AND id_dens.density_g_per_ml IS NOT NULL THEN
                rt.quantity * rt.multiplier * su.to_base_factor * id_dens.density_g_per_ml / NULLIF(du.to_base_factor, 0)
            WHEN su.dimension = 'mass' AND du.dimension = 'volume' AND id_dens.density_g_per_ml IS NOT NULL THEN
                rt.quantity * rt.multiplier * su.to_base_factor / id_dens.density_g_per_ml / NULLIF(du.to_base_factor, 0)
            -- Unconvertible dimensions remain in their original unit_id.
            ELSE
                rt.quantity * rt.multiplier
        END AS converted_quantity
    FROM recipe_tree rt
    JOIN ingredients i ON i.id = rt.ingredient_id
    JOIN units su ON su.id = rt.unit_id
    LEFT JOIN units du ON du.id = i.default_unit_id
    LEFT JOIN ingredient_densities id_dens ON id_dens.ingredient_id = rt.ingredient_id AND id_dens.notes IS NULL
    WHERE rt.ingredient_id IS NOT NULL
)
SELECT
    ingredient_id,
    unit_id,
    SUM(converted_quantity) AS total_quantity
FROM normalized
GROUP BY ingredient_id, unit_id
`

type ResolveRecipeTreeRow struct {
	IngredientID  pgtype.UUID `json:"ingredient_id"`
	UnitID        interface{} `json:"unit_id"`
	TotalQuantity int64       `json:"total_quantity"`
}

// Resolves all leaf ingredients from a recipe's full sub-recipe tree
// and aggregates total quantities per ingredient, normalizing to default unit.
// Normalize quantities to each ingredient's default unit
func (q *Queries) ResolveRecipeTree(ctx context.Context, recipeID pgtype.UUID) ([]ResolveRecipeTreeRow, error) {
	rows, err := q.db.Query(ctx, resolveRecipeTree, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveRecipeTreeRow{}
	for rows.Next() {
		var i ResolveRecipeTreeRow
		if err := rows.Scan(&i.IngredientID, &i.UnitID, &i.TotalQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompiledRecipes = `-- name: SearchCompiledRecipes :many
SELECT cr.recipe_id, cr.compiled_at, cr.is_stale,
       cr.compiled_steps, cr.compiled_grocery_list,
       cr.compiled_nutrition_per_serving, cr.compiled_nutrition_total,
       cr.compiled_allergens, cr.compiled_diet_flags,
       cr.total_active_seconds, cr.total_passive_seconds, cr.total_calories_per_serving,
       cr.compiled_tags, cr.compiled_from_revision_id,
       cr.compiled_allergens_contains, cr.compiled_allergens_may_contain, cr.compile_input_hash,
       cr.compile_schema_version,
       r.title, r.slug, r.description, r.servings, r.yield_amount, r.yield_unit_id,
       r.source_locale, r.visibility,
       r.author_id, r.created_at AS recipe_created_at, r.updated_at AS recipe_updated_at
FROM compiled_recipes cr
JOIN recipes r ON r.id = cr.recipe_id
WHERE r.visibility = 'public'
  AND (r.title ILIKE '%' || $1 || '%' OR r.description ILIKE '%' || $1 || '%')
ORDER BY r.created_at DESC
LIMIT $2
`

type SearchCompiledRecipesParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type SearchCompiledRecipesRow struct {
	RecipeID                    pgtype.UUID        `json:"recipe_id"`
	CompiledAt                  pgtype.Timestamptz `json:"compiled_at"`
	IsStale                     bool               `json:"is_stale"`
	CompiledSteps               []byte             `json:"compiled_steps"`
	CompiledGroceryList         []byte             `json:"compiled_grocery_list"`
	CompiledNutritionPerServing []byte             `json:"compiled_nutrition_per_serving"`
	CompiledNutritionTotal      []byte             `json:"compiled_nutrition_total"`
	CompiledAllergens           []string           `json:"compiled_allergens"`
	CompiledDietFlags           []string           `json:"compiled_diet_flags"`
	TotalActiveSeconds          int32              `json:"total_active_seconds"`
	TotalPassiveSeconds         int32              `json:"total_passive_seconds"`
	TotalCaloriesPerServing     pgtype.Numeric     `json:"total_calories_per_serving"`
	CompiledTags                []string           `json:"compiled_tags"`
	CompiledFromRevisionID      pgtype.UUID        `json:"compiled_from_revision_id"`
	CompiledAllergensContains   []string           `json:"compiled_allergens_contains"`
	CompiledAllergensMayContain []string           `json:"compiled_allergens_may_contain"`
	CompileInputHash            pgtype.Text        `json:"compile_input_hash"`
	CompileSchemaVersion        int32              `json:"compile_schema_version"`
	Title                       string             `json:"title"`
	Slug                        string             `json:"slug"`
	Description                 pgtype.Text        `json:"description"`
	Servings                    int32              `json:"servings"`
	YieldAmount                 pgtype.Numeric     `json:"yield_amount"`
	YieldUnitID                 pgtype.UUID        `json:"yield_unit_id"`
	SourceLocale                string             `json:"source_locale"`
	Visibility                  string             `json:"visibility"`
	AuthorID                    pgtype.UUID        `json:"author_id"`
	RecipeCreatedAt             pgtype.Timestamptz `json:"recipe_created_at"`
	RecipeUpdatedAt             pgtype.Timestamptz `json:"recipe_updated_at"`
}

func (q *Queries) SearchCompiledRecipes(ctx context.Context, arg SearchCompiledRecipesParams) ([]SearchCompiledRecipesRow, error) {
	rows, err := q.db.Query(ctx, searchCompiledRecipes, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCompiledRecipesRow{}
	for rows.Next() {
		var i SearchCompiledRecipesRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.CompiledAt,
			&i.IsStale,
			&i.CompiledSteps,
			&i.CompiledGroceryList,
			&i.CompiledNutritionPerServing,
			&i.CompiledNutritionTotal,
			&i.CompiledAllergens,
			&i.CompiledDietFlags,
			&i.TotalActiveSeconds,
			&i.TotalPassiveSeconds,
			&i.TotalCaloriesPerServing,
			&i.CompiledTags,
			&i.CompiledFromRevisionID,
			&i.CompiledAllergensContains,
			&i.CompiledAllergensMayContain,
			&i.CompileInputHash,
			&i.CompileSchemaVersion,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Servings,
			&i.YieldAmount,
			&i.YieldUnitID,
			&i.SourceLocale,
			&i.Visibility,
			&i.AuthorID,
			&i.RecipeCreatedAt,
			&i.RecipeUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublicRecipes = `-- name: SearchPublicRecipes :many
SELECT id, author_id, title, slug, description, servings, visibility, source_locale, created_at, updated_at, yield_amount, yield_unit_id FROM recipes
WHERE visibility = 'public'
  AND (title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2
`

type SearchPublicRecipesParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchPublicRecipes(ctx context.Context, arg SearchPublicRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, searchPublicRecipes, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Servings,
			&i.Visibility,
			&i.SourceLocale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.YieldAmount,
			&i.YieldUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompiledRecipe = `-- name: UpsertCompiledRecipe :exec
INSERT INTO compiled_recipes (
    recipe_id, compiled_at, is_stale,
    compiled_steps, compiled_grocery_list,
    compiled_nutrition_per_serving, compiled_nutrition_total,
    compiled_allergens, compiled_allergens_contains, compiled_allergens_may_contain, compiled_diet_flags,
    total_active_seconds, total_passive_seconds, total_calories_per_serving,
    compiled_tags, compile_input_hash, compile_schema_version
) VALUES ($1, now(), false, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (recipe_id) DO UPDATE SET
    compiled_at = now(),
    is_stale = false,
    compiled_steps = EXCLUDED.compiled_steps,
    compiled_grocery_list = EXCLUDED.compiled_grocery_list,
    compiled_nutrition_per_serving = EXCLUDED.compiled_nutrition_per_serving,
    compiled_nutrition_total = EXCLUDED.compiled_nutrition_total,
    compiled_allergens = EXCLUDED.compiled_allergens,
    compiled_allergens_contains = EXCLUDED.compiled_allergens_contains,
    compiled_allergens_may_contain = EXCLUDED.compiled_allergens_may_contain,
    compiled_diet_flags = EXCLUDED.compiled_diet_flags,
    total_active_seconds = EXCLUDED.total_active_seconds,
    total_passive_seconds = EXCLUDED.total_passive_seconds,
    total_calories_per_serving = EXCLUDED.total_calories_per_serving,
    compiled_tags = EXCLUDED.compiled_tags,
    compile_input_hash = EXCLUDED.compile_input_hash,
    compile_schema_version = EXCLUDED.compile_schema_version
`

type UpsertCompiledRecipeParams struct {
	RecipeID                    pgtype.UUID    `json:"recipe_id"`
	CompiledSteps               []byte         `json:"compiled_steps"`
	CompiledGroceryList         []byte         `json:"compiled_grocery_list"`
	CompiledNutritionPerServing []byte         `json:"compiled_nutrition_per_serving"`
	CompiledNutritionTotal      []byte         `json:"compiled_nutrition_total"`
	CompiledAllergens           []string       `json:"compiled_allergens"`
	CompiledAllergensContains   []string       `json:"compiled_allergens_contains"`
	CompiledAllergensMayContain []string       `json:"compiled_allergens_may_contain"`
	CompiledDietFlags           []string       `json:"compiled_diet_flags"`
	TotalActiveSeconds          int32          `json:"total_active_seconds"`
	TotalPassiveSeconds         int32          `json:"total_passive_seconds"`
	TotalCaloriesPerServing     pgtype.Numeric `json:"total_calories_per_serving"`
	CompiledTags                []string       `json:"compiled_tags"`
	CompileInputHash            pgtype.Text    `json:"compile_input_hash"`
	CompileSchemaVersion        int32          `json:"compile_schema_version"`
}

func (q *Queries) UpsertCompiledRecipe(ctx context.Context, arg UpsertCompiledRecipeParams) error {
	_, err := q.db.Exec(ctx, upsertCompiledRecipe,
		arg.RecipeID,
		arg.CompiledSteps,
		arg.CompiledGroceryList,
		arg.CompiledNutritionPerServing,
		arg.CompiledNutritionTotal,
		arg.CompiledAllergens,
		arg.CompiledAllergensContains,
		arg.CompiledAllergensMayContain,
		arg.CompiledDietFlags,
		arg.TotalActiveSeconds,
		arg.TotalPassiveSeconds,
		arg.TotalCaloriesPerServing,
		arg.CompiledTags,
		arg.CompileInputHash,
		arg.CompileSchemaVersion,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name, category)
VALUES ($1, $2)
ON CONFLICT (name, category) DO UPDATE SET updated_at = now()
RETURNING id
`

type UpsertTagParams struct {
	Name     string `json:"name"`
	Category string `json:"category"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.Name, arg.Category)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
